# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a86903cd7e0616fea2dd122346bf8bd087e922fd302184bf3ce2ff97c95e265a43d845d6ec3db3531d8f97d2a95f705dc95ec36d059be39e9feeebef85f5e24f

test:
  secret_key_base: 9059ad1570cbbb8ca50a100aa89b30633a55953530042ceb40acc3888761fbbc9af2135ea4554cb59b136e17c49431a79350226a9f7a35c2d3d00a3d0e1a58e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
